version: "3.7"
services:
  pp-keycloak:
    build:
      context: ${PARTICIPANT_PORTAL_KEYCLOAK_DIR}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
  pp-keycloak-vue:
    build:
      context: ${PARTICIPANT_PORTAL_FE_DIR}
    ports:
      - "3000:3000"
  rems:
    build:
      context: ${REMS_DIR}
      dockerfile: Dockerfile
    mem_reservation: 200m
    mem_limit: 500m
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./services/rems/simple-config.edn:/rems/config/config.edn
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_reservation: 30m
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"
  rp-keycloak:
    build:
      context: ${RESEARCHER_PORTAL_KEYCLOAK_DIR}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "3002:8080"
