version: "3.7"
services:
  keycloak:
    build:
      context: services/keycloak/
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
  keycloak-vue:
    build:
      context: services/sample-vue/app-vue/
    ports:
      - "3000:3000"