version: "3.7"
services:
  keycloak:
    build:
      context: ${PARTICIPANT_PORTAL_KEYCLOAK_DIR}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
  keycloak-vue:
    build:
      context: ${PARTICIPANT_PORTAL_FE_DIR}
    ports:
      - "3000:3000"
